# Exercise 2 Numpy Solution

1) Import numpy package

In [1]:
import numpy as np

2) Create a list of size 10 with all zeros

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Create a 3 X 3 Matrix with values ranging from 0 to 8

In [5]:
y = np.arange(9).reshape(3, 3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4) Create a 3 X 3 X 3 array with random values 

In [6]:
z = np.random.random ((3,3,3))
print(z)

[[[0.90364815 0.02473651 0.65251375]
  [0.61888226 0.32017219 0.25403573]
  [0.55826401 0.24311761 0.47284552]]

 [[0.87444247 0.80100716 0.69261039]
  [0.04103457 0.87073416 0.06402796]
  [0.64068291 0.06968456 0.31502028]]

 [[0.81134471 0.78165645 0.02677342]
  [0.0372013  0.23153897 0.79625762]
  [0.47456003 0.83582664 0.98761217]]]


5) Create a 5 X 5 array with random values.  Find the minimum and maximum values.

In [7]:
z = np.random.random((5,5))
print(z)
print(z.min())
print(z.max())

[[0.9182764  0.8700646  0.73001946 0.37334    0.81391145]
 [0.13146162 0.75164138 0.02847779 0.56031353 0.53327935]
 [0.23503913 0.29720164 0.19502088 0.66506946 0.34496925]
 [0.8979567  0.48644916 0.39189096 0.68516149 0.43562407]
 [0.51094515 0.1622206  0.10715744 0.398931   0.91036114]]
0.028477788446095054
0.9182764030718559


6) Create an array of 10 random values.  Rearrange the arrange in order.

In [8]:
x = np.random.random((10))
print(x)
x =  np.sort(x)
print(x)

[0.14917243 0.40661254 0.13557928 0.0125985  0.40592119 0.18277726
 0.06393413 0.3392624  0.96596443 0.22971182]
[0.0125985  0.06393413 0.13557928 0.14917243 0.18277726 0.22971182
 0.3392624  0.40592119 0.40661254 0.96596443]


7) Create an array of 10 random values.  Get the sum and average value of the elements.

In [9]:
x = np.random.random((10))
print(x)
print(np.sum(x))
print(np.average(x))


[0.35571583 0.74870444 0.49646159 0.44566435 0.72821208 0.95468843
 0.86479721 0.60801248 0.04308338 0.00332195]
5.248661746820806
0.5248661746820806
