# NumPy 

NumPy (stands for Numerical Python) is a general packages used for processing arrays. It provides a high performance, multidimensional array object and tools to work with these arrays and is popular for scientific computing in Python.

Importing NumPy library for use in our Python code.

In [2]:
import numpy as np

NumPy array is a grid of values and values are indexed via a set of zero-based non-negative integers. NumPy arrays can be initiated from Python lists.

In [3]:
# [10, 20, 30] is a Python list.
# x is a NumPy array.
x = np.array ([10, 20, 30]) # rank is the number of dimensions in the array

Printing the data-type of NumPy arrays.

In [4]:
print(type(x))

<class 'numpy.ndarray'>


The shape of a NumPy array gives the lengths of element-dimensions in the array.

In [5]:
print(x.shape)  # size of x is a 1-dimensional numpy array

(3,)


 Accessing array elements with indices.

In [7]:
print(x[0], x[1]) 

10 20


Changing an array element via an index.

In [8]:
x[0] = 40 # changing array element

print(x)

[40 20 30]


Creating an array of rank 2.

In [24]:
y = np.array([[10, 20, 30], [40, 50, 60]])

y

array([[10, 20, 30],
       [40, 50, 60]])

Printing the (Row, Column) dimensions of the array.

In [25]:
print(y.shape)  # returns number of elements in the array

(2, 3)


Accessing individual elements for the first row of the array.

In [11]:
print (y[0, 0], y[0, 1], y[1, 2])

10 20 60


Creating an array of Zeros.

In [26]:
x = np.zeros((2, 2))
print(x)

[[0. 0.]
 [0. 0.]]


Creating a NumPy array that contains the value of 1.0.

In [27]:
y = np.ones((1, 2))  # create a 1x2 array of ones.
print(y)

[[1. 1.]]


Creating a NumPy array filled with a certain value.

In [28]:
z = np.full((2, 2), 7) # Return a 2x2 array filled with the value 7
print(z)

[[7 7]
 [7 7]]


Creating a NumPy Identity array (diagonal of ones)

In [32]:
a = np.eye(3) # create an identify matrix, 3X3
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Creating a NumPy array of random floats between 0.0 and 1.0.

In [43]:
b = np.random.random((2, 3)) # create an array of random values

print(b)

[[0.65198439 0.45466311 0.18038534]
 [0.16534793 0.7733163  0.15909966]]


Creating a 4x3 NumPy array of random integers between 5 and 19 (note the half-open interval: [low, high)).

In [44]:
c = np.random.randint(low=5, high=20, size=(4, 3))

print(c)

[[ 6  9  8]
 [11 15 10]
 [ 9 16  8]
 [19 18 16]]


We can force a NumPy to have a certain dimensions that is different from the given Python List. The following creates a 2-Dimension NumPy array even though a 1-Dimensional Python List is passed in.

In [45]:
myarray = np.array([10, 20, 30, 40], ndmin=2) #ndmin=2, minimum dimensions is 2

print(myarray)

[[10 20 30 40]]


Loading a text file into a NumPy array.

In [49]:
# skiprows=1 skipping the first row
# unpack=True returns the columns as separate arrays
x, y = np.loadtxt('../dataset/budget1.txt', skiprows=1, unpack=True)

print(x)
print(y)

[100. 200. 300. 400.]
[200. 300. 400. 500.]


All missing datas can be filled with a default value.

In [53]:
# filling missing data with the value -999
array2 = np.genfromtxt('../dataset/budget2.txt', skip_header=1, filling_values =-999) 

print(array2)

# refer to the doc https://numpy.org/devdocs/user/basics.io.genfromtxt.html#filling-values


[[ 100.  200.]
 [ 200. -999.]
 [ 300.  400.]
 [ 400.  500.]]


Saving files with NumPy.

In [54]:
array1 = np.arange(start=0.1, stop=7.4, step=2.5) # create an array with starting value, increment value (step), and stop before value 10 is reached
print(array1)

# save data in text file
np.savetxt('../dataset/out_data.txt', array1, fmt='%f')  # specify the format to be floating point

# refer to https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html


[0.1 2.6 5.1]


Performing numerical calculations with NumPy.

In [57]:
a = np.ones((2, 3))
print(a)

b = np.random.random((2, 3))
print(b)

# element-wise addition
print(a+b)

# element-wise subtraction
print(a-b)

# element-wise multiplication
print(a*b)

# element-wise division
print(a/b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0.57837576 0.07953614 0.2422536 ]
 [0.04084054 0.59926881 0.05665215]]
[[1.57837576 1.07953614 1.2422536 ]
 [1.04084054 1.59926881 1.05665215]]
[[0.42162424 0.92046386 0.7577464 ]
 [0.95915946 0.40073119 0.94334785]]
[[0.57837576 0.07953614 0.2422536 ]
 [0.04084054 0.59926881 0.05665215]]
[[ 1.72897979 12.57290115  4.1279057 ]
 [24.4854715   1.66870023 17.65157994]]


Accessing elements in a NumPy array.

In [69]:
x = np.array ([[0, 1, 2], [3, 4, 5]])

print(x)

[[0 1 2]
 [3 4 5]]


Accessing indivdiual rows.

In [71]:
print(x[1])  # all elements of index 1 (row 1)

[3 4 5]


Slicing a NumPy array by providing 'row' and 'column'.

In [72]:
print(x[0, 2])  # element at row 0, column 2

2


Slicing a NumPy array using a range takes the form M[a:b,c:d], where M is the NumPy array, 'a' and 'b' are start and end Row indices, and 'c' and 'd' are start and end Column indices. Note that 'b' and 'd' are non-inclusive.

In [79]:

print(x[0:2, 0:2]) # elements between row 0 and 1, column 0 and 1


[[0 1]
 [3 4]]


In [81]:
print(x[0:2, 1:2]) # elements between row 0 and 1, and column 1 

[[1]
 [4]]


If the range values are not specified, then it defaults to getting everything.

In [85]:
# the 'end' range for the column is not specified, hence all columns after 1 is retrieved.
print(x[0:1,1:]) 

[[1 2]]


Re-arranging our NumPy array where rows are now columns, and columns are now rows.

In [62]:
print(np.transpose(x))  # transposing the array, which means switch around the array shape


[[0 3]
 [1 4]
 [2 5]]
