# Numpy 

Numpy (stands for Numerical Python) is a general packages used for processing arrays. It provides a high performance, multidimensional array object and tools to work with these arrays and is popular for scientific computing in Python.

Importing NumPy library for use in our Python code.

In [1]:
import numpy as np

Numpy array is a grid of values and values are indexed via a set of zero-based non-negative integers.  

NumPy arrays can be initiated from nested Python list.

In [2]:
x = np.array ([10, 20, 30]) # rank is the number of dimensions in the array

In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [4]:
print(x.shape)  # size of the numpy array

(3,)


In [5]:
print(x[0], x[1])  # accessing array elements with indexis

10 20


In [6]:
x[0] = 40 # changing array element

In [7]:
print(x) 

[40 20 30]


In [8]:
y = np.array([[10, 20, 30], [40, 50, 60]])  # create an array of rank 2

In [9]:
print(y.shape)  # returns number of elements in the array

(2, 3)


In [10]:
print (y[0, 0], y[0, 1], y[1, 2])

10 20 60


In [11]:
x = np.zeros((2, 2)) #create an array of zeros
print(x)

[[0. 0.]
 [0. 0.]]


In [12]:
y = np.ones((1, 2))  # create an array of ones
print(y)

[[1. 1.]]


In [13]:
z = np.full((2, 2), 7) # Return a array filled with the value 7
print(z)

[[7 7]
 [7 7]]


In [14]:
a = np.eye(3) # create an identify matrix, 3X3
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
b = np.random.random((2, 2)) # create an array of random values
print(b)

[[0.80402078 0.75001309]
 [0.16309077 0.7667008 ]]


In [16]:
myarray = np.array([10, 20, 30, 40], ndmin=2) #ndmin =2, minimum dimensions is 2
print(myarray)

[[10 20 30 40]]


In [17]:
x,y = np.loadtxt('data.txt', skiprows=1, unpack=True) # load dataset from text file,
                                                    # skip the first row,
                                                    # unpack = True returns the columns as separate arrays
    

OSError: data.txt not found.

In [ ]:
print(x)
print(y)

In [ ]:
array2 = np.genfromtxt('data2.txt', skip_header=1,filling_values =-999) # missing value will be -999
print(array2)

# refer to the doc https://numpy.org/devdocs/user/basics.io.genfromtxt.html#filling-values


In [ ]:
array1 = np.arange(start=0.1, stop=7.4, step=2.5) # create an array with starting value, increment value (step), and stop before value 10 is reached
print(array1)

# save data in text file
np.savetxt('out_data.txt', array1, fmt='%f')  # specify the format to be floating point
# refer to https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html


In [ ]:
a = np.ones ((2, 3))
print(a)

b = np.random.random((2, 3))
print(b)

print(a+b)

print(a-b)

print(a*b)

print(a/b)


In [ ]:
x = np.array ([[0, 1, 2], [3, 4, 5]])
print(x)
print(x[1])  # all elements of index 1 (row 1)
print(x[0][2])  # element at row 0, column 0
print(x[0:2, 1]) # element at row 0 and 1 (2-1), column 1
print(np.transpose(x))  # transposing the array, which means switch around the array shape
